#ifndef _ODRL_
#define _ODRL_

#pragma once

/* Generated with cbindgen:0.28.0 */

// This file is autogenerated by cbindgen. Don't modify it manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


int32_t enable_verbose(int32_t verbose);

int32_t delete_odrl_world(int64_t *ptr);

int64_t create_odrl_world(const char *odrl);

#endif  /* _ODRL_ */
