#ifndef _ODRL_
#define _ODRL_

#pragma once

/* Generated with cbindgen:0.28.0 */

// This file is autogenerated by cbindgen. Don't modify it manually.

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


int32_t add(int32_t a,
            int32_t b);

void hello(void);

#endif  /* _ODRL_ */
